/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface CheckAddressPromisedMintsResponse {
  airdrop_mint_in_progress: boolean;
  airdrop_mint_is_closed: boolean;
  claimed_mint_count: number;
  minter_addr: Addr;
  promised_mint_count: number;
}
export interface CheckAddressPromisedTokensResponse {
  address_claimed_token_ids: TokenMsg[];
  address_promised_token_ids: TokenMsg[];
  airdrop_mint_in_progress: boolean;
  airdrop_mint_is_closed: boolean;
  minter_addr: Addr;
}
export interface TokenMsg {
  collection_id: number;
  token_id: number;
}
export type Timestamp = Uint64;
export type Uint64 = string;
export interface Config {
  admin: Addr;
  end_time?: Timestamp | null;
  maintainer_addr?: Addr | null;
  start_time: Timestamp;
}
export type ExecuteMsg = {
  update_config: InstantiateMsg;
} | {
  update_maintainer_address: string | null;
} | {
  add_promised_token_ids: AddressTokenMsg[];
} | {
  remove_promised_token_ids: TokenMsg[];
} | {
  remove_promised_tokens_by_address: string[];
} | {
  add_promised_mints: AddressValMsg[];
} | {
  remove_promised_mints: string[];
} | {
  mark_token_id_claimed: AddressTokenMsg;
} | {
  increment_address_claimed_promised_mint_count: string;
};
export interface InstantiateMsg {
  end_time?: Timestamp | null;
  maintainer_address?: string | null;
  start_time: Timestamp;
}
export interface AddressTokenMsg {
  address: string;
  token: TokenMsg;
}
export interface AddressValMsg {
  address: string;
  value: number;
}
export type GetAddressPromisedMintsResponse = AddressValMsg[];
export type GetAddressPromisedTokenIdsResponse = AddressPromisedTokensResponse[];
export interface AddressPromisedTokensResponse {
  address: string;
  token_ids: TokenMsg[];
}
export type GetAssignedTokenIdsResponse = TokenMsg[];
export type GetAssignedTokenIdsWithAddressResponse = AddressTokenMsg[];
export type GetClaimedAddressPromisedMintsResponse = AddressValMsg[];
export type GetClaimedTokenIdsResponse = TokenMsg[];
export type GetClaimedTokenIdsWithAddressResponse = AddressTokenMsg[];
export interface GetConfigResponse {
  admin: Addr;
  end_time?: Timestamp | null;
  maintainer_addr?: Addr | null;
  start_time: Timestamp;
}
export type QueryMsg = {
  get_config: {};
} | {
  get_address_promised_token_ids: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  get_assigned_token_ids: {
    limit?: number | null;
    start_after?: [number, number] | null;
  };
} | {
  get_assigned_token_ids_with_address: {
    limit?: number | null;
    start_after?: [number, number] | null;
  };
} | {
  get_claimed_token_ids: {
    limit?: number | null;
    start_after?: [number, number] | null;
  };
} | {
  get_claimed_token_ids_with_address: {
    limit?: number | null;
    start_after?: [number, number] | null;
  };
} | {
  get_address_promised_mints: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  get_claimed_address_promised_mints: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  check_address_promised_mints: {
    minter_address: string;
  };
} | {
  check_address_promised_tokens: {
    minter_address: string;
  };
};