/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export type Addr = string;
export interface CheckWhitelistResponse {
  current_mint_count: number;
  is_on_whitelist: boolean;
  max_per_address_mint: number;
  mint_price: Uint128;
  minter_addr: Addr;
  whitelist_in_progress: boolean;
  whitelist_is_closed: boolean;
}
export type Timestamp = Uint64;
export type Uint64 = string;
export interface Config {
  admin: Addr;
  end_time: Timestamp;
  maintainer_addr?: Addr | null;
  max_per_address_mint: number;
  max_whitelist_address_count: number;
  mint_price: Uint128;
  start_time: Timestamp;
}
export type ExecuteMsg = {
  update_config: InstantiateMsg;
} | {
  update_maintainer_address: string | null;
} | {
  add_to_whitelist: string[];
} | {
  remove_from_whitelist: string[];
} | {
  update_address_mint_tracker: string;
};
export interface InstantiateMsg {
  end_time: Timestamp;
  maintainer_address?: string | null;
  max_per_address_mint: number;
  max_whitelist_address_count: number;
  mint_price: Uint128;
  start_time: Timestamp;
}
export type GetAddressMintsResponse = [string, number][];
export interface GetConfigResponse {
  admin: Addr;
  end_time: Timestamp;
  maintainer_addr?: Addr | null;
  max_per_address_mint: number;
  max_whitelist_address_count: number;
  mint_price: Uint128;
  start_time: Timestamp;
  whitelist_address_count: number;
  whitelist_in_progress: boolean;
  whitelist_is_closed: boolean;
}
export type GetWhitelistAddressesResponse = string[];
export type QueryMsg = {
  get_config: {};
} | {
  check_whitelist: {
    minter_address: string;
  };
} | {
  get_whitelist_addresses: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  get_address_mints: {
    limit?: number | null;
    start_after?: string | null;
  };
};