/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.20.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface CheckAddressPromisedMintsResponse {
  airdrop_mint_in_progress: boolean;
  airdrop_mint_is_closed: boolean;
  claimed_mint_count: number;
  minter_addr: Addr;
  promised_mint_count: number;
  [k: string]: unknown;
}
export interface CheckAddressPromisedTokensResponse {
  address_claimed_token_ids: number[];
  address_promised_token_ids: number[];
  airdrop_mint_in_progress: boolean;
  airdrop_mint_is_closed: boolean;
  minter_addr: Addr;
  [k: string]: unknown;
}
export type Timestamp = Uint64;
export type Uint64 = string;
export interface Config {
  admin: Addr;
  end_time?: Timestamp | null;
  maintainer_addr?: Addr | null;
  start_time: Timestamp;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  update_config: InstantiateMsg;
} | {
  update_maintainer_address: string | null;
} | {
  add_promised_token_i_ds: AddressValMsg[];
} | {
  remove_promised_token_i_ds: number[];
} | {
  remove_promised_tokens_by_address: string[];
} | {
  add_promised_mints: AddressValMsg[];
} | {
  remove_promised_mints: string[];
} | {
  mark_token_i_d_claimed: [string, number];
} | {
  increment_address_claimed_promised_mint_count: string;
};
export interface InstantiateMsg {
  end_time?: Timestamp | null;
  maintainer_address?: string | null;
  start_time: Timestamp;
  [k: string]: unknown;
}
export interface AddressValMsg {
  address: string;
  value: number;
  [k: string]: unknown;
}
export type GetAddressPromisedMintsResponse = AddressValMsg[];
export interface GetAddressPromisedTokenIDsResponse {
  address: string;
  token_ids: number[];
  [k: string]: unknown;
}
export type GetAssignedTokenIDsResponse = number[];
export type GetAssignedTokenIDsWithAddressResponse = AddressValMsg[];
export type GetClaimedAddressPromisedMintsResponse = AddressValMsg[];
export type GetClaimedTokenIDsResponse = number[];
export type GetClaimedTokenIDsWithAddressResponse = AddressValMsg[];
export interface GetConfigResponse {
  admin: Addr;
  end_time?: Timestamp | null;
  maintainer_addr?: Addr | null;
  start_time: Timestamp;
  [k: string]: unknown;
}
export type QueryMsg = {
  get_config: {
    [k: string]: unknown;
  };
} | {
  get_address_promised_token_i_ds: {
    limit?: number | null;
    start_after?: string | null;
    [k: string]: unknown;
  };
} | {
  get_assigned_token_i_ds: {
    limit?: number | null;
    start_after?: number | null;
    [k: string]: unknown;
  };
} | {
  get_assigned_token_i_ds_with_address: {
    limit?: number | null;
    start_after?: number | null;
    [k: string]: unknown;
  };
} | {
  get_claimed_token_i_ds: {
    limit?: number | null;
    start_after?: number | null;
    [k: string]: unknown;
  };
} | {
  get_claimed_token_i_ds_with_address: {
    limit?: number | null;
    start_after?: number | null;
    [k: string]: unknown;
  };
} | {
  get_address_promised_mints: {
    limit?: number | null;
    start_after?: string | null;
    [k: string]: unknown;
  };
} | {
  get_claimed_address_promised_mints: {
    limit?: number | null;
    start_after?: string | null;
    [k: string]: unknown;
  };
} | {
  check_address_promised_mints: {
    minter_address: string;
    [k: string]: unknown;
  };
} | {
  check_address_promised_tokens: {
    minter_address: string;
    [k: string]: unknown;
  };
};